In [15]:
import os
import pandas as pd
import numpy as np
import math
from datetime import datetime

In [16]:
from platform import python_version
print(python_version())

3.8.8

### Recuperando datos

In [17]:
# Reclamos
file_name = 'data/pre_processed_2_sbs.csv'
datos_preprocessed = pd.read_pickle(file_name)

In [34]:
# Trimestres
datos_preprocessed['Trimestre'] = str(datos_preprocessed['fecha_fase1'].dt.year)+'-'+str(datos_preprocessed['fecha_fase1'].dt.quarter)

In [50]:
datos_preprocessed['Trimestre'] = datos_preprocessed['fecha_fase1'].apply(lambda x: str(x.year)+'-'+str(x.quarter))

In [57]:
data_temp = datos_preprocessed.groupby(['Trimestre','Nivel','Reclamo/requerim']).agg({'NÂ° Reclamo': "count"})
data_temp = data_temp.sort_values(by=['Trimestre']).reset_index()
data_temp

   Trimestre Nivel Reclamo/requerim  NÂ° Reclamo
0     2018-1   1er          RECLAMO        6837
1     2018-1   1er    REQUERIMIENTO          58
2     2018-1   2do          RECLAMO        2473
3     2018-1   2do    REQUERIMIENTO         484
4     2018-2   1er          RECLAMO        6272
5     2018-2   1er    REQUERIMIENTO          61
6     2018-2   2do          RECLAMO        2151
7     2018-2   2do    REQUERIMIENTO         462
8     2018-3   1er          RECLAMO        6464
9     2018-3   1er    REQUERIMIENTO          62
10    2018-3   2do          RECLAMO        2622
11    2018-3   2do    REQUERIMIENTO         457
12    2018-4   2do    REQUERIMIENTO         379
13    2018-4   2do          RECLAMO        3303
14    2018-4   1er          RECLAMO       13224
15    2018-4   1er    REQUERIMIENTO         106
16    2019-1   1er          RECLAMO        8949
17    2019-1   1er    REQUERIMIENTO          37
18    2019-1   2do          RECLAMO        1730
19    2019-1   2do    REQUERIMIENTO         310
20    2019-2   1er          RECLAMO        3133
21    2019-2   1er    REQUERIMIENTO          14
22    2019-2   2do          RECLAMO         850
23    2019-2   2do    REQUERIMIENTO          48
24    2019-3   1er          RECLAMO        8561
25    2019-3   1er    REQUERIMIENTO          71
26    2019-3   2do          RECLAMO        2065
27    2019-3   2do    REQUERIMIENTO         457
28    2019-4   2do    REQUERIMIENTO         477
29    2019-4   2do          RECLAMO        2283
30    2019-4   1er    REQUERIMIENTO          89
31    2019-4   1er          RECLAMO       11007
32    2020-1   1er          RECLAMO        9508
33    2020-1   1er    REQUERIMIENTO         497
34    2020-1   2do          RECLAMO        2087
35    2020-1   2do    REQUERIMIENTO         543
36    2020-2   1er          RECLAMO       20935
37    2020-2   1er    REQUERIMIENTO         834
38    2020-2   2do          RECLAMO        2631
39    2020-2   2do    REQUERIMIENTO        3393
40    2020-3   1er          RECLAMO       18716
41    2020-3   1er    REQUERIMIENTO         601
42    2020-3   2do          RECLAMO        3133
43    2020-3   2do    REQUERIMIENTO        4363
44    2020-4   2do    REQUERIMIENTO        2878
45    2020-4   2do          RECLAMO        3450
46    2020-4   1er    REQUERIMIENTO         557
47    2020-4   1er          RECLAMO       27269
48    2021-1   1er          RECLAMO       30652
49    2021-1   1er    REQUERIMIENTO        1258
50    2021-1   2do          RECLAMO        4147
51    2021-1   2do    REQUERIMIENTO        2243
52    2021-2   1er          RECLAMO       11306
53    2021-2   1er    REQUERIMIENTO        1175
54    2021-2   2do          RECLAMO        3672
55    2021-2   2do    REQUERIMIENTO         957
56    2021-3   1er          RECLAMO        3680
57    2021-3   1er    REQUERIMIENTO          74
58    2021-3   2do          RECLAMO        1691
59    2021-3   2do    REQUERIMIENTO         312

In [61]:
data_temp = datos_preprocessed.groupby(['Trimestre','Nivel']).agg({'NÂ° Reclamo': "count"})
data_temp = data_temp.sort_values(by=['Trimestre']).reset_index()
data_temp.set_index("Trimestre", inplace = True)

data_temp
#data_temp.plot(kind="bar", stacked=True)

          Nivel  NÂ° Reclamo
Trimestre
2018-1      1er        6895
2018-1      2do        2957
2018-2      1er        6333
2018-2      2do        2613
2018-3      1er        6526
2018-3      2do        3079
2018-4      1er       13330
2018-4      2do        3682
2019-1      1er        8986
2019-1      2do        2040
2019-2      1er        3147
2019-2      2do         898
2019-3      1er        8632
2019-3      2do        2522
2019-4      2do        2760
2019-4      1er       11096
2020-1      1er       10005
2020-1      2do        2630
2020-2      1er       21769
2020-2      2do        6024
2020-3      1er       19317
2020-3      2do        7496
2020-4      1er       27826
2020-4      2do        6328
2021-1      1er       31910
2021-1      2do        6390
2021-2      1er       12481
2021-2      2do        4629
2021-3      1er        3754
2021-3      2do        2003

In [21]:
datos_preprocessed['fecha_fase1'].dt.year

0         2018
1         2018
2         2019
3         2019
4         2019
          ...
248053    2021
248054    2021
248055    2021
248056    2021
248057    2021
Name: fecha_fase1, Length: 248058, dtype: int64

In [ ]:
datos_preprocessed['fecha_fase1'].dt.quarter

#### Recuperando codigos SBS